version: "3.9"
services:
  front:
    image: sermalenk/skypro-front:lesson-34
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"
  api:
    image: ivanim/diploma_todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    restart: always
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      SECRET_KEY: $SECRET_KEY
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    env_file:
      - ./.env
  migrations:
    image: ivanim/diploma_todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    command: python manage.py migrate
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - todolist_postgres_data:/var/lib/postgresql/data

volumes:
  todolist_postgres_data:
