version: "3.9"
services:
  front:
    image: sermalenk/skypro-front:lesson-34
    depends_on:
      - api
    ports:
      - "80:80"
  api:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    env_file:
      - .env
  migrations:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.env:/app/.env
    command: python manage.py migrate
  postgres:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./todolist_postgres_data:/var/lib/postgresql/data

volumes:
  todolist_postgres_data:
