version: "3.9"
services:
  main_todolist_db:
    image: postgres:12.4-alpine
    volumes:
      - todolist_postgres_data:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
      - POSTGRES_DB=todolist
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=111111
      - POSTGRES_HOST=localhost

volumes:
  todolist_postgres_data:
