# Generated by Django 4.0.1 on 2022-12-14 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_board_category_board_boardparticipant'),
    ]

    operations = [
    ]
