# Generated by Django 4.0.1 on 2022-12-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_create_new_objects'),
        ('goals', '0005_create_new_objects'),
    ]

    operations = [
    ]
