# Generated by Django 4.0.1 on 2023-01-05 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TgUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('username', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('verification_code', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='код подтверждения')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tg пользователь',
                'verbose_name_plural': 'Tg пользователи',
            },
        ),
    ]
